### ISSUE TITLE
Is identity actually created from hash of public key, not private key? Not forgeable?

### ISSUE THREAD

**Issue by jeffbski** [ssbc/secure-scuttlebutt#100]
I haven't looked into the code, but going off of the info in the readme, "identity is created from a hash on your public key" which leads me to this question:

**Since public keys are shared, if someone can determine how to perform the hash (including any salt) then can't they easily forge your identity?**

I would have assumed that the identity would be created as a hash off the **private key**.

---

https://github.com/ssbc/secure-scuttlebutt#identity

## Identity

Each node's identity is represented by the hash of their public key. Although they are not "human readable", this does guarantee that you get unique identifiers (without a central registry) and it's infeasible for anyone to forge your identity.

**Comment by pfraze** [comment]
Hi Jeff, thanks for the concern. Happy to say that's not how it works.

The pubkey hash is an identifier, not a mechanism for proving ownership of the keypair, or for proving authorship of a message. It's used only to refer to the keypair in a space-efficient way.

In SSB, identity is determined by your ability to produce well-formed messages with a valid signature. You might say your identity is what you publish. If the signature on your message doesn't match the author ID you claim on the message, then it's a bad message, and it won't be accepted by anybody. 

Signatures are produced by the private key, then validated with the public key, so identity is a matter of possessing the private key. So long as you've kept the private key safe, it should not be possible for anybody else to publish messages under your ID (which is what "identity forgery" would look like).

> "identity is created from a hash on your public key"

To clarify, that is @jeffbski's summary of the readme, not a direct quote, which is good because it's inaccurate. "Each node's identity is represented by the hash of their public key" is the direct quote.

Hope that clears it up!

**Comment by jeffbski** [comment]
@pfraze Thanks for the clarification.

**Comment by dominictarr** [comment]
good question @jeffbski is there a way we can make this clearer in the readme?

**Comment by jeffbski** [comment]
@dominictarr Maybe it would help to include a little more of what @pfraze mentioned above. Not too much detail but mentioning the signatures and identity requiring the private key. 

I guess the proximity of identity being a hash of public key, and infeasible to forge is what raised the question. It skipped over the signatures and private key use that happens in between there and makes things secure.
