### ISSUE TITLE
Increase message size limit?

### ISSUE THREAD

**Issue by pfrazee** [ssbc/secure-scuttlebutt#110]
1kb is not very convenient. Consider...
- Headers are ~300 bytes, 30%
- Links are ~50 bytes, 5%

People generally want the size limit removed from phoenix (me included).
I don't want to rely on blobs to avoid the post limit, since blobs is less stable and has more edgecases.
also devs would be happier with more space to work with

Why 1kb vs (say) 15kb?

**Comment by dominictarr** [comment]
when we set the limit we had a binary encoding, and those overheads where smaller.
I agree lets make it larger, but not too large. i'd be happy with 2k, 4k, or 8k?
I think 15 is too big... just because it's *meant* to be small, and 15k isn't small anymore...
Hmm... I think 15k is not small to be because I wouldn't consider a 15k js file to be small.

**Comment by dominictarr** [comment]
nor a 15k blog post

**Comment by pfraze** [comment]
yeah, I just like the head-room that 15k gives. we can still hold the philosophy that messages are small without making it a technical enforcement, esp if there's not a strong need to do 8 vs 15

**Comment by dominictarr** [comment]
we can always make it larger but we can't make it smaller again...

**Comment by entron** [comment]
@dominictarr what are the problems caused by an even larger message size limit such as 64K or 128K? I think SSB is a great platform for publishing and I know one can always use blobs. However using blobs requests all clients implement a seperate logic. If a larger limit does not cause much harm why should we impose kind of an artificial limit on a decentralized protocol? Based on some studies such as this and this the average blog post length is 1236 words which is about 8K and the most engaging blogs posts has lenght 2500+ (16KB+). These are just average or optimal values not the values which will cover most typlical uses cases. In many serious topics such as science, history etc longer post are very typical. Can we gradually incresed the lenght to 64K or 128K?
