### ISSUE TITLE
Consensus on SSB

### ISSUE THREAD

**Issue by lukeburns** [ssbc/secure-scuttlebutt#122]
Is it possible to build a consensus mechanism on top of SSB?

**Comment by dominictarr** [comment]
of course. ssb is just a mechanism for replicating secure (signed) logs. (though you'd want to start from https://github.com/ssbc/scuttlebot to get replication)

what sort of consensus structure do you have in mind?

**Comment by lukeburns** [comment]
Probably PBFT: http://www.pmg.lcs.mit.edu/papers/osdi99.pdf. I'm interested in secure p2p transactions.

**Comment by pfraze** [comment]
@lukeburns it may be easier if I gave an overview of the network

You can look at SSB as an eventually-consistent database. The blockchain entries are gossiped in a mesh of peers, and partitions do not block local progress. The expectation is, this is a global network of user devices, and nodes will frequently go down. When choosing consensus and data structures, start by looking at EC literature.

We do not have a metric for the "freshness" of a blockchain entry. Entries are timestamped, but timestamps are not reliable and can easily be forged. Barring a future change, there's no mechanism built into SSB to determine if you have the latest entry published by some other user. 

On ordering: SSB's blockchains are isolated; there's one for each user. This means that chains maintain their own total order, and are only able to provide partial orders between each other. Partial order happens through content-address references: you can link to a message on another blockchain by referring to its hash, and this implies a `happens-before` relationship. (This is because, content-hashes can only exist after the content exists.)

I haven't researched transactions on EC systems enough to speak definitively on them. You may need stronger guarantees. We plan to expose SSB's networking stack to the application layer, and so you'll be able to create your own secure connections and create CP (highly-consistent) clusters. With this, you can develop separate protocols, or add guarantees to the blockchain which are only possible via direct connections.

**Comment by lukeburns** [comment]
Oh, so eventual consistency makes things tricky. Can you direct me towards work on EC that would be useful for understanding SSB?

**Comment by pfraze** [comment]
These are some notes about EC and CRDTs https://github.com/pfraze/crdt_notes
