### ISSUE TITLE
getPublicKey is incorrect

### ISSUE THREAD

**Issue by pfraze** [ssbc/secure-scuttlebutt#129]
`getPublicKey` is no longer correct, because we don't publish an `init` message anymore.

We can either rewrite it to extract the pubkey out of the ID, or we can remove it. I'm in favor of the former, in case we decide to use pubkey hashes again in the future.

**Comment by dominictarr** [comment]
lets just remove it. We'd have to commit to that possibility and tell everyone to call that method, but they wouldn't because it's easier to just grab it off the message, indeed that is what we do internally!

stability levels are described in the stability module, which i pulled from the node.js stability index.
which seems quite reasonable, after a discussion about nuances of semver (whether v1.0 has a special meaning)

[unstable](https://github.com/dominictarr/stability#unstable) means there may be features, patches, and possibly breaks, [stable](https://github.com/dominictarr/stability#stable) means do not expect breaks.

I'm inclined to say `stable`, given the choices, but in all honesty, I do think we may have a breaking change. If it was entirely up to me, i'd lable it "pretty stable". Although, that is not part of the stability index spec!

HOWEVER! I am the maintainer of the stability module, and it's stability is marked as _stable_ so we could make _additions_ to the spec without contradicting the meaning of "stable", and we can add various qualifiers for the manner of the maintainers eagerness to change the module, then we could call it "pretty stable" or "hopefully stable". We can't rule out breaking changes, but hopefully won't make them.

**Comment by pfraze** [comment]
:+1:
