### ISSUE TITLE
Link functionality as its own library?

### ISSUE THREAD

**Issue by paulkernfeld** [ssbc/secure-scuttlebutt#137]
It seems to me that secure-scuttlebutt would still be a very useful tool even without the built-in linking functionality. And, as far as I can tell, the linking functionality depends on the feed functionality but not vice versa. So... what if the linking lived in its own separate library that depended on secure-scuttlebutt? Or, alternatively, if the linking lived in the [scuttlebot](https://github.com/ssbc/scuttlebot) repo? This would have the advantage of reducing the complexity of secure-scuttlebutt.

Is this a useful thing to do?

**Comment by pfraze** [comment]
Also a good question. The only practical effect of links is to automatically populate link-indexes with them. Those indexes are in the core library because links are part of the basic spec, so the question is, should links be in the base spec?

I think they should be, because they're a pretty fundamental pattern, and it's good to have all ssb programs agree on that pattern. Arguments against?

**Comment by paulkernfeld** [comment]
I don't think this is a super important issue, but here's an argument against.

In the Kappa Architecture, the streams are the canonical data store, and you add whatever optimized queries on top of them. SSB feeds are the canonical stores, and SSB links are an example of a way facilitate certain optimized queries: you can ask for all the stuff that a feed links to, or you can use the reverse index to see all the feeds that link to a particular thing. This is a useful set of queries for many applications, but I can imagine a lot of other great use cases for SSB that require different indices, or that don't require indices at all. For example, maybe I'm doing some social network analysis, and I need an efficient graph database. Maybe I'm writing a news app, and I need a full-text search engine. Maybe I'm creating a P2P Yelp, and I need a geospatial index.  Maybe I don't want efficient indices at all because I have an extremely write-heavy application!

Obviously, SSB is never going to meet all of these use cases, but I don't think it needs to try to do so, since there are already many good tools for creating these indices. So maybe it makes sense to split the query-optimization stuff into a layer that runs of top of SSB, so that SSB is a little simpler. Does that make any sense?

**Comment by pfraze** [comment]
It does make sense, you describe it correctly. I think we ended up including these because they were convenient to have in core, but they're not necessary, and we know non-trivial apps will need their own indices. Where are you on this, @dominictarr ? I remember you brought it up a bit ago.

**Comment by dominictarr** [comment]
this does sound fairly reasonable, actually I have been thinking about changing the pattern that indexes are generated. These oneshot indexes are easy (say, index everything a post links to) because you can generate the correct index immediately (so generating the index is sync) but there are lots of other things that you can't do. Like, generating a count of all the records in the database. To generate the count, you need to know the current value, which you don't have in a one shot index.

On the other hand, this is fairly stable right now (in the sense that I havn't had to make changes in a while). And currently, this is only being used by scuttlebot, so probably there are some sbot related things tied in here that don't need to be... if another project built on this, that would be great to guide the change, because it would show what was most useful.
