### ISSUE TITLE
Documentation: use of blockchain terminology

### ISSUE THREAD

**Issue by mitar** [ssbc/secure-scuttlebutt#161]
I am reading through documentation and do not know much about the project, so if this was discussed somewhere already, sorry, and feel free to just point me to it.

But I think it is a bit confusing that you use term "blockchain" for the chain of blocks scuttlebutt is using. I mean, I agree it is a chain of blocks (or better, hashchain of blocks), but it is not a blockchain like most of the people these days understand it (so hashchain of blocks + consensus protocol to resolve conflicts).

I have seen that sometimes you are using block-chain, which is maybe a bit better, but it is not consistent.

Anyway, I think that the best terminology would be [hashchain](https://en.wikipedia.org/wiki/Hash_chain) of blocks, or maybe block hashchain. Or maybe Merkle chain? :-) Because each block can reference other chains as well, maybe a Merkle DAG is suitable as well.

To conclude, I think that for novice user it might look like scuttlebutt provides more, a full forest of blockchain feeds, one blockchain per user, with all the properties they expect from blockchains. From my understanding, this is not true.

**Comment by evbogue** [comment]
I've heard the individual append-only logs referred to as 'sigchains' in the past. 

Where in the documentation are you referencing?

**Comment by mitar** [comment]
https://ssbc.github.io/secure-scuttlebutt/

**Comment by dominictarr** [comment]
this is a good point.

There is no consensus algorithm, which is different from "blockchain" (athough "block" doesn't have anything to do with consensus all the things calling themselves "blockchain" happen to have consensus)

git has a "hashchain" which is just a tree of objects that contain the hashes of previous objects.

in git there are no signatures by default, but you can use them - if you forced them on, and rejected any unsigned objects then it would be very close to what we have.

so a "singly linked signature chain" (because you arn't allowed to make a forking tree structure)
