### ISSUE TITLE
ephemeral messages

### ISSUE THREAD

**Issue by dominictarr** [ssbc/secure-scuttlebutt#24]
A channel for communication outside of replication would be useful for on-boarding new users https://github.com/pfraze/phoenix/issues/22

This could also be utilized for allowing a limited capacity to push messages to a node,
for example, sometimes you want people that do not follow you to be able to send you a message, one way to secure this would be to route messages through the social network,
A can send a message to C my sending through their mutual friend B. Then C can read the message and choose to follow A.

**Comment by mnzaki** [comment]
Hello from the future :smile: any love for this issue recently?

**Comment by ahdinosaur** [comment]
hi @mnzaki!

you might be interested in @dominictarr's tech tree: [%kDrsaJXkDiRwit9mCCmqoWBqI3WWxBxp+82fjZELluU=.sha256](https://viewer.scuttlebot.io/%25kDrsaJXkDiRwit9mCCmqoWBqI3WWxBxp%2B82fjZELluU%3D.sha256). i single out Dominic because unfortunately he still is the one who disproportionately does ssb protocol work and has the best understanding.

with my understanding, the current strategy is to use the pubs as signaling servers to bootstrap a direct connection (over tcp or webrtc) betweens peers, so they can send all the ephemeral messages they want as a separate protocol on the side.

**Comment by dominictarr** [comment]
yeah, I'm too flooded with improving the core protocol stuff, so I'm not expecting to have time to implement this soon.
