### ISSUE TITLE
app kit :)

### ISSUE THREAD

**Issue by karissa** [ssbc/secure-scuttlebutt#68]
it'd be nice to have some intro guidelines around how one might create a custom app on the protocol

**Comment by sfrdmn** [comment]
+1 Having a hard time figuring what the "does one thing well" is here. Stuff like [this](https://github.com/ssbc/secure-scuttlebutt/blob/52313fdd6590a70420bb36fe5b9f7ffc539a461f/index.js#L249) makes it smell like it's biased towards social network type applications rather than a general purpose distributable DB. Also [scuttle*bot*](https://github.com/ssbc/scuttlebot/blob/b9186f10900385066fcf23e6e164707b54c36812/README.md) refers to SSB as a data network, but SSB refers back to scuttlebot as its networking layer... and then scuttlebot has this app specific UI thing...

All I'm really looking for is a DB using scuttlebutts to store data, which I'm pretty sure this is? But I'm getting sent in circles trying to confirm that.

**Comment by dominictarr** [comment]
What kind of data do you have? the problem my be that there is no such thing as a "general purpose distributable DB"

SSB is designed the way it is, because it takes a bunch of relatively simple ideas (signed chains + ordered log replication + gossip protocols) and combines them in a way that is useful for _somethings_.
(everything about ssb is compromised towards making the distributed part work really well)

@sfrdmn you could argue that it is -- not "biased", but suited -- towards social networks because the core data structure secure-scuttlebutt implements is very close to what underlies all social network applications. I.e. each user gets a feed, and nodes can replicate other feeds. replicate just some feeds, the feeds of actors you trust/like, and that is a social network. (in twitter, fb, ln, the UX at least feels like this)

If you replicated _all_ the feeds, or chose the feeds to replicate to my some non-social way, it might still work.

If you can describe what data you have and what you are trying to do with it, I can help you understand how you could represent that with ssb.

**Comment by sfrdmn** [comment]
> What kind of data do you have? the problem my be that there is no such thing as a "general purpose distributable DB"

Ah, OK, interesting. Then just sufficiently general!

> you could argue that it is -- not "biased", but suited -- towards social networks

Woops, yah. Biased is a bad word :)

> If you can describe what data you have and what you are trying to do with it, I can help you understand how you could represent that with ssb.

Sweet, thanks. I'm looking into making a flavor of [camlistore](http://camlistore.org/) (which you've probably seen, but anyway: it's a content-addressable data store with mutation via chains of immutable transactions). It's a *personal* data store, though, and its network would consist of potentially many machines with *one* owner, with any sort of external sharing as a secondary feature. Basically, just need to store metadata on content-addressable blobs as well as metadata to build various graphs of those blobs. Have looked at this, CouchDB, [dat](https://github.com/maxogden/dat), [Tahoe-LAFS](https://en.wikipedia.org/wiki/Tahoe-LAFS), and camlistore itself. Multi-master replication is needed to account for the many devices a single user may have.

**Comment by dominictarr** [comment]
@sfrdmn okay cool, can you make that more concrete? like what *is* the data, like, what is your example applicaiton? I find that when you make it more concrete I can suddenly apply all the knowledge I already possess to that thing, where as if we discuss something abstractly we are much more limited for context. Making it concrete is like using `require`.

**Comment by sfrdmn** [comment]
Yah, hmm... OK the application I'm thinking about is more or less a [Memex](https://en.wikipedia.org/wiki/Memex) for myself (and others if it gets so far). You can imagine the UI as a black hole in which you drag arbitrary blobs, annotating them with metadata over which views / graphs / views of graphs can be built. Focus is probably on web clippings, notes, images, PDFs... Could be code or any other type which has a view implemented for it. A sort of decentralized Evernote with extensible views + the responsibility of making stored data redundant. Personal cloud kinda thing.

Hopefully concrete example:
Drag an image of a walnut into the app. A new root node is created containing the content-hash address of the image. Next I drag the image of the walnut into a set of such blobs called "trying to figure out walnuts". This set is itself an object with a root node and mutation chain. A transaction is created on top of the chain of mutations for that set, adding the new walnut image as a member of the set (via its address)... and these changes (at least, the metadata) are then gossiped (I guess?) to the other clients I may have, and maybe the blobs are shipped to various endpoints for redundancy.

**Comment by dominictarr** [comment]
@sfrdmn okay! Now I can clearly picture your application and think about how you would implement it with ssb.

So the walnut image is a message with an attachment - the message contains the hash of the picture, and some metadata. Then you associate it with a set, you can think about this like a thread. There is a message that represents the start of the "walnut project" and then you post a message that ties the thread to the image. in ssb, all links are indexed, so you can traverse these links and get a set of posts that are cryptographically related. 

One thing we have discussed, but havn't really implemented in phoenix yet is to show all backlinks in the UI. Like how on github, each issue shows references from other issues that mention it. I think a lot of applications would "fall out" of a backlink system (i.e. package manager + forums = issue tracker, if you can associate the threads with the package, and be notified about them)

[scuttlebot](https://github.com/ssbc/scuttlebot) already provides support for blob replication.

**Comment by dominictarr** [comment]
@sfrdmn also come hangout in #scuttlebutt (freenode) if you have any more questions!
