### ISSUE TITLE
A more constrained link definition in message objects

### ISSUE THREAD

**Issue by pfraze** [ssbc/secure-scuttlebutt#94]
per discussion on irc, 
The `rel` attribute on links seems burdensome when we can just put links in sub-objects and infer the rel-type from the attribute name. I believe @dominictarr feels the same.

We discussed -and I now propose -we restrict links from appearing in the top object, and remove the `rel` attribute instead. A sub-object will then be determined to be a link by looking for `feed`, `msg`, and `ext`, which may be used in any combination on the sub-object. The relation type will be the key of the sub-object in its immediate parent.

For example, this message --

```json
  "content": {
    "type": "post",
    "text": "hello @dominic",
    "repliesTo": {
      "msg": "xhoAEBPnmEN2+kfTYrUrb6G0Q/Nc7x9lc0WB9UskoGk=.blake2s",
      "rel": "replies-to"
    },
    "mentions": [
      {
        "feed": "wuDDnMxVtk8U9hrueDj/T0itgp5HJZ4ZDEJodTyoMdg=.blake2s",
        "rel": "mentions",
        "name": "dominic"
      }
    ]
  }
```

changes to--

```json
  "content": {
    "type": "post",
    "text": "hello @dominic",
    "repliesTo": {
      "msg": "xhoAEBPnmEN2+kfTYrUrb6G0Q/Nc7x9lc0WB9UskoGk=.blake2s"
    },
    "mentions": [
      {
        "feed": "wuDDnMxVtk8U9hrueDj/T0itgp5HJZ4ZDEJodTyoMdg=.blake2s",
        "name": "dominic"
      }
    ]
  }
```

In this case, it is structurally similar -- it's only dropped the `rel`. Other messages will have to change structure. For instance:

```json
"content": {
  "type": "follow",
  "rel": "follows",
  "feed": "wuDDnMxVtk8U9hrueDj/T0itgp5HJZ4ZDEJodTyoMdg=.blake2s"
}
```

Will become

```json
"content": {
  "type": "follow",
  "follows": {
    "feed": "wuDDnMxVtk8U9hrueDj/T0itgp5HJZ4ZDEJodTyoMdg=.blake2s"
  }
}
```

--

As an aside, I'm also considering a semantic refactor for the message types, in which case follow may become something more like:

```json
"content": {
  "type": "follow",
  "newFriend": {
    "feed": "wuDDnMxVtk8U9hrueDj/T0itgp5HJZ4ZDEJodTyoMdg=.blake2s"
  }
}
// and for unfollow:
"content": {
  "type": "unfollow",
  "oldFriend": {
    "feed": "wuDDnMxVtk8U9hrueDj/T0itgp5HJZ4ZDEJodTyoMdg=.blake2s"
  }
}
```

But that's not related to this topic (unless we want it to be)

**Comment by dominictarr** [comment]
+1 on posts and mentions.

Should we make the relations more generic? like, post could use `append.msg = <post_id>` or `updates.msg = <post>`
that could be then used in any object type which works by appending?

For other data structures, I'm thinking about this:

``` js
var task = { //first task
  type: 'task'
  ...
}

{
  type: 'taskmod',
  object: hash(task),
  updates: hash(task)
}
```

A thread could be considered an aggregation of messages, like any other datastructure...
using generic properties to represent this simplifies scemantics, and indexes.
So we could use `object` and `updates` on posts... the only thing about posts/threads being that they are updated by appending, instead of merging...

Likewise, a follows message is really about creating or deleting a link between you and another feed.
In this way, it's simpler to have just one message type (follows) which can be either positive or negative - we can retrive it with one query, and just aggregate the messages (unfollows just looks like `type: 'follows', follows: {feed: <id>, retracted: true}`)

It reads less like english, but it means there will be less code...

**Comment by pfraze** [comment]
I like the idea of using more generic relations, but I think we need to be careful.

I wouldn't want to use `updates` for a reply because it's not inconceivable that we add message edits (even if we don't plan to now) in which case `updates` would be my natural choice.

I'm ok with using only one type -- I think we can keep it readable with the rels.
For instance, what about...

```
{ type: 'follow', followed: { feed: ... } }
{ type: 'follow', unfollowed: { feed: ... } }
{ type: 'trust', trusted: { feed: ... } }
{ type: 'trust', untrusted: { feed: ... } }
{ type: 'trust', flagged: { feed: ... } }
{ type: 'trust', unflagged: { feed: ... } }
{ type: 'name', name: 'bob', assignee: { feed: ... } }
{
  type: 'post',
  text: 'this is a reply',
  root: { msg: ... }, // top of thread
  parent: { msg: ... }, // immediate parent
  mentioned: [{ feed: ... }],
  attachment: [{ ext: ... }]
}
```

**Comment by dominictarr** [comment]
if there are two rels that is a more complicated index, or two queries merged.
``` js
{ type: 'trust', trust: { feed: Y } }
{ type: 'trust', trust: { feed: Y , revoke: true } }
```
then we can just query all feed relations from X to Y, via an index on trust.feed, or even check whether X trusts Y with just a single query.

@pfraze hmm, when I said `updates` i was thinking about something that was part of the "object" but joined the object after the message it updated. maybe it would be better to call that `appends`?
It's more about representing the causal order, so that we can detect consistency.

The more important thing is actually the `object` link, because that is about retriving all the messages that mutate that object (the thread, in the case of posts). Then we need the causal ordering link, by the time we are making a distinction between adding a comment, and updating a comment, that it certainly an application level concern.

**Comment by pfraze** [comment]
> then we can just query all feed relations from X to Y, via an index on trust.feed, or even check whether X trusts Y with just a single query.

Ok, that's sound

> It's more about representing the causal order, so that we can detect consistency.

That's inherent in links, the relation semantics are orthogonal.

> The more important thing is actually the object link, because that is about retriving all the messages that mutate that object (the thread, in the case of posts).

I agree, but I prefer `root` to `object` and `parent` to `updates` or `appends` because they represent the tree structure more specifically while remaining generic. 

> by the time we are making a distinction between adding a comment, and updating a comment, that it certainly an application level concern.

Yes but relation semantics are application semantics. It's not a huge issue (on par with "what to name this api function") but I think `root` and `parent` are more clear.

**Comment by dominictarr** [comment]
@pfraze okay I'm on board with `root` and `parent`.

**Comment by dominictarr** [comment]
@pfraze on second thoughts, `root` and `parent` mixes vocabulary, `root` from trees, and `parent` from lineage.
should be: `root` `branch` `leaf` or `ancestor` `parent` `child`. I'm in favor of `root/branch/leaves`

**Comment by pfraze** [comment]
I do appreciate the consistency. My argument for `root` and `parent` is that's the same semantics used in the unix file-system to indicate ancestor directories.

**Comment by dominictarr** [comment]
right. I needed to extend the metaphore, and talk about the dangling ends of the tree. git calls these "heads".
what has a Root, Parents, and Heads???

Root, Branches, and Leaves is way more sensible

**Comment by ahdinosaur** [comment]
:deciduous_tree: :+1:

**Comment by pfraze** [comment]
Ok, let's get started on this monster! I think I can do this without breaking backwards compatibility, but that would mean our standard is a blend of the two approaches: basically, that `rel` is optional, and (let's say) takes priority over the keyname. Does that sound ok, or would we rather break backwards compat?

As for the updates, I'm going to hit https://github.com/ssbc/ssb-msgs to support this new scheme. I'll update https://github.com/ssbc/secure-scuttlebutt as needed after. Then, I'll update https://github.com/ssbc/ssb-msg-schemas, and then phoenix and my personal apps. Did I miss anything?

**Comment by dominictarr** [comment]
@pfraze I think we can skip full backwards compat, and maybe limit it to backwards compat with what phoenix actually does, but not what the code does? so it's compatible with how the code was used, but not everything that it could do. This works because we happened to use `<rel>: {msg, rel: <rel>}`* anyway

*excusing camel casing.

**Comment by pfraze** [comment]
@dominictarr almost -- some messages do, but we've got a lot of messages shaped like this:

```js
{ type: 'follow', rel: 'follows', feed: $hash }
```

**Comment by dominictarr** [comment]
oh. if we make it back compat we  will have to carry that code around forever, and we have only just start, and there are only like 20 people who have installed this? we can just refollow them.

**Comment by pfraze** [comment]
Ok. So everybody understands, this change will cause you to lose the following data:

 - Follows
 - Trusts
 - Flags
 - Names given to other users

**Comment by pfraze** [comment]
@dominictarr shall we do a deep search for links, or must links be subobjects of the top object?

I propose the latter, such that links are either in the form:

```js
{ type: 'type', myLink: { feed/msg/ext: ... } }
```

or:

```
{ type: 'type', myLink: [{ feed/msg/ext: ... }] }
```

I also propose that the link type is case-insensitive, and that all handling code lowercases the `rel` before processing it.

**Comment by ahdinosaur** [comment]
+1 for proposed form, that's JSON-LD. :octopus: 

i think we shouldn't worry about back compat, but this does bring up the delightful question of ssb data migrations, which would allow us to change the structure of our data without losing data and without having to worry about back compat.

**Comment by dominictarr** [comment]
@ahdinosaur in this case, we'd need an active migration, where clients must republish old content in the new form. We can't do it in general because we can't recreate someone elses signature.

**Comment by ahdinosaur** [comment]
@dominictarr ah true, hmm.

**Comment by pfraze** [comment]
@ahdinosaur dominic's correct, but we can still write a migration tool, which I plan to do https://github.com/ssbc/phoenix/issues/341

**Comment by pfraze** [comment]
@dominictarr this has been fully implemented, close issue?
